### PR TITLE
TurtleShroom Productions Proudly Presents: Mutual V1.3 AND V1.4 Compatibility

### PR DESCRIPTION
**Pull request by TurtleShroom**
[DELETED]

### CODE REVIEW

**Comment by joseasoler** [comment]
This PR includes modifications unrelated to the proposed feature. It adds files that shouldn't be committed to the repository, and it also modifies the README and other key files of the project to prominently add the name of the author of the PR. Because of these reasons I believe it should not be merged.

The official RimWorld documentation for multi-version compatibility should help in properly implementing this feature. It can be found here: https://docs.google.com/document/d/e/2PACX-1vSOOrF961tiBuNBIr8YpUvCWYScU-Wer3h3zaoMrw_jc8CCjMjlMzNCAfZZHTI2ibJ7iUZ9_CK45IhP/pub

**Comment by Georodin** [comment]
Actually I was doing the update while I was very tiered and simply forgot about it. And I haven't played rimworld in a while, which contributed to forgetting about the downward compability. I already updated the steam version for now with a mini update.

I will add the multi version support for the git version as well, but with just one additional assembly file. Because like stated in the last commit, I did nothing else but to replace the references to 1.4 for the update. 
Thanks for your time.

**Comment by TurtleShroom** [comment]
> Because like stated in the last commit, I did nothing else but to replace the references to 1.4 for the update. Thanks for your time.

It was a pleasure to help. Thank you for making such a great Mod.

**Comment by TurtleShroom** [comment]
> This PR includes modifications unrelated to the proposed feature. It adds files that shouldn't be committed to the repository

Every file I put back was in the Mod and was intended by the author of the Mod to be there. The Source folder and such is in any Mod that uses C-Sharp and excluding it would be messing with the author's work. When I was adding back the V1.3 version, those files were part of it. For that reason, and with the intent of avoiding any changes to the actual Mod, I preserved them.

> It also modifies the README and other key files of the project to prominently add the name of the author of the PR. Because of these reasons I believe it should not be merged.

There's a reason behind this, actually. I quietly attribute myself in the code because I consider it immoral to outright demand credit and accolades on the actual Steam Page where everyone can see. After all, I didn't need public fame or recognition to do this.

I _greatly_ overstepped myself when I put it in the Readme, I will admit, but I was going so fast that I didn't think about it at the time.

**Comment by TurtleShroom** [comment]
> I will add the multi version support for the git version as well, but with just one additional assembly file. Because like stated in the last commit, I did nothing else but to replace the references to 1.4 for the update. Thanks for your time.

I checked the updated version you mentioned, and it seems the only thing you did was change the ABOUT file. Are you against adding V1.3 support back? Is there some other, more subtle way to add V1.3 support that I missed?

**Comment by TurtleShroom** [comment]
@Georodin 

OP, I was told by several people that the way I worded things was dishonorable, and that I was being rude. I wish to deeply and sincerely apologize to you and anyone else who worked on this Mod; I had absolutely no ill will and didn't mean to hurt anyone.

I hope you can forgive me. It was an accident.

**Pull request closed without merging**
